### ISSUE TITLE
how do i connect it to my server?

### ISSUE THREAD

**Issue by LuiteCoder** [Galaxy1036/GalaxyLifeReborn#9]

**Comment by Galaxy1036** [comment]
You can either edit your /etc/hosts file if your device is rooted and redirect ios.galaxylifegame.com to your local ip or manually patch the url in the game library

**Comment by LuiteCoder** [comment]
Thanks.

**Comment by LuiteCoder** [comment]
um so i cant see it in /etc/host on a rooted emulator.
